/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciamento_de_biblioteca;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author AndreyFernandesTraja
 */
public class F_Comentarios extends javax.swing.JFrame {

    /**
     * Creates new form F_Comentarios
     */
    public F_Comentarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lbl_livro = new javax.swing.JLabel();
        lbl_idcoment = new javax.swing.JLabel();
        lbl_comentario = new javax.swing.JLabel();
        txt_livro = new javax.swing.JTextField();
        txt_coment = new javax.swing.JTextField();
        bt_cadastrar = new javax.swing.JButton();
        bt_pesquisar = new javax.swing.JButton();
        bt_atualizar = new javax.swing.JButton();
        bt_deletar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_comentario = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_livro.setText("ID_Livro:");

        lbl_idcoment.setText("ID_Comentario:");

        lbl_comentario.setText("Comentario:");

        bt_cadastrar.setText("Cadastrar");
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });

        bt_pesquisar.setText("Pesquisar");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        bt_atualizar.setText("Atualizar");
        bt_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizarActionPerformed(evt);
            }
        });

        bt_deletar.setText("Deletar");
        bt_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarActionPerformed(evt);
            }
        });

        txt_comentario.setColumns(20);
        txt_comentario.setRows(5);
        jScrollPane3.setViewportView(txt_comentario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_livro)
                        .addGap(48, 48, 48)
                        .addComponent(txt_livro)
                        .addGap(197, 197, 197))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_idcoment)
                            .addComponent(lbl_comentario))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_coment)
                                .addGap(197, 197, 197))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_cadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_pesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_atualizar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_deletar)
                        .addGap(0, 34, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_livro)
                    .addComponent(txt_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idcoment)
                    .addComponent(txt_coment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_comentario)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cadastrar)
                    .addComponent(bt_pesquisar)
                    .addComponent(bt_atualizar)
                    .addComponent(bt_deletar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarActionPerformed
        // TODO add your handling code here:
        /*try
        {
            int Livro = Integer.parseInt(txt_livro.getText());
            int Coment = Integer.parseInt(txt_coment.getText());
            String Comentario = txt_comentario.getText(); 
        } 
        catch (NumberFormatException a) 
        {
            System.out.println("Erro no formato do valor");
            System.out.println(a.fillInStackTrace());
        }
        catch (Exception e)
        {
            System.out.println("ERRO!!! Foi mal :)");
            System.out.println(e.fillInStackTrace());
        }*/
        try {
            txt_comentario.setLineWrap(true);
            String driverName = "com.mysql.jdbc.Driver";
            Class.forName(driverName);
            String servidor = "193.123.108.138"; //caminho do servidor do BD
            String database = "progb2022"; //nome do banco de dados
            String url = "jdbc:mysql://" + servidor + "/" + database + "?useUnicode=true&characterEncoding=UTF8";
            System.out.println(url);
            String username = "progb2022";
            String senha = "progb2022";
            Connection conn = DriverManager.getConnection(url, username, senha);
            Statement stmt = conn.createStatement();
            int Livro = Integer.parseInt(txt_livro.getText());
            int Coment = Integer.parseInt(txt_coment.getText());
            String Comentario = txt_comentario.getText();
            String sql  = "INSERT INTO andrey_comentarios(id_livro,id_comentario,comentario) VALUES('"+Livro+"','"+Coment+"','"+Comentario+"');";
            System.out.println(sql);
            stmt.execute(sql);            ///preparaco da insercao do registro
            conn.close();
            System.out.println("Salvo no Banco");
            
            
            
        } catch (Exception e){
            System.out.println("erro"+e.getLocalizedMessage());
                        System.out.println("erro"+e.getStackTrace());
        }
        
    }//GEN-LAST:event_bt_cadastrarActionPerformed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        // TODO add your handling code here:
        try
        {
            System.out.println("Botão Pesquisar");  
        }
        catch (NumberFormatException a) 
        {
            System.out.println("Erro no formato do valor");
            System.out.println(a.fillInStackTrace());
        }
        catch (Exception e)
        {
            System.out.println("ERRO!!! Foi mal :)");
            System.out.println(e.fillInStackTrace());
        }
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void bt_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizarActionPerformed
        // TODO add your handling code here:
        try
        {
            System.out.println("Botão Atualizar");
            String sql = "UPDATE andrey_comentarios SET nome= 'pATATI pATATA', idade  = 'Rua Tamandare do pe do ze', telefone  = '99', email = 'afasfa@gmail.com' endereco = '9914160215' WHERE ID =  42;";
        }
        catch (NumberFormatException a) 
        {
            System.out.println("Erro no formato do valor");
            System.out.println(a.fillInStackTrace());
        }
        catch (Exception e)
        {
            System.out.println("ERRO!!! Foi mal :)");
            System.out.println(e.fillInStackTrace());
        }
    }//GEN-LAST:event_bt_atualizarActionPerformed

    private void bt_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarActionPerformed
        // TODO add your handling code here:
        try {
        String drivername = "com.mysql.jdbc.Driver"; /// driver
        String servidor   = "193.123.108.138"; // 
        String database   = "progb";
        String url        = "jdbc:mysql://193.123.108.138/progb2022";
        String usuario    = "progb2022";
        String senha      = "progb2022";
        Connection conexao  =  DriverManager.getConnection(url,usuario,senha);
        Statement stmt  =  conexao.createStatement();
        String sql = "DELETE FROM andrey_comentarios WHERE id = 1";
        System.out.println(sql);
        stmt.execute(sql);
        stmt.close();       
        
         
        } catch (Exception e) {
            System.out.println("Erro Generico = "+e.fillInStackTrace());
        }
    }//GEN-LAST:event_bt_deletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Comentarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_atualizar;
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_deletar;
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_comentario;
    private javax.swing.JLabel lbl_idcoment;
    private javax.swing.JLabel lbl_livro;
    private javax.swing.JTextField txt_coment;
    private javax.swing.JTextArea txt_comentario;
    private javax.swing.JTextField txt_livro;
    // End of variables declaration//GEN-END:variables
}
