/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciamento_de_biblioteca;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author AndreyFernandesTraja
 */
public class F_Livro extends javax.swing.JFrame {

    /**
     * Creates new form F_Livro
     */
    public F_Livro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_livro = new javax.swing.JLabel();
        txt_livro = new javax.swing.JTextField();
        lbl_autor = new javax.swing.JLabel();
        txt_autor = new javax.swing.JTextField();
        lbl_genero = new javax.swing.JLabel();
        txt_genero = new javax.swing.JTextField();
        lbl_editora = new javax.swing.JLabel();
        txt_editora = new javax.swing.JTextField();
        bt_cadastrar = new javax.swing.JButton();
        bt_pesquisar = new javax.swing.JButton();
        bt_atualizar = new javax.swing.JButton();
        bt_deletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_id.setText("ID:");

        lbl_livro.setText("Livro:");

        txt_livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_livroActionPerformed(evt);
            }
        });

        lbl_autor.setText("Autor:");

        txt_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_autorActionPerformed(evt);
            }
        });

        lbl_genero.setText("Genero:");

        lbl_editora.setText("Editora");

        bt_cadastrar.setText("Cadastrar");
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });

        bt_pesquisar.setText("Pesquisar");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        bt_atualizar.setText("Atualizar");
        bt_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizarActionPerformed(evt);
            }
        });

        bt_deletar.setText("Deletar");
        bt_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_livro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_livro)
                            .addComponent(txt_id)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_autor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_autor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_genero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_genero))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_editora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_editora)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_cadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(bt_pesquisar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(bt_atualizar)
                .addGap(18, 18, 18)
                .addComponent(bt_deletar)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_livro)
                    .addComponent(txt_livro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_autor)
                    .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_genero)
                    .addComponent(txt_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_editora)
                    .addComponent(txt_editora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cadastrar)
                    .addComponent(bt_pesquisar)
                    .addComponent(bt_atualizar)
                    .addComponent(bt_deletar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_autorActionPerformed

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarActionPerformed
        // TODO add your handling code here:
        /*try
        {
           int id = Integer.parseInt(txt_id.getText());
           String Livro = txt_livro.getText();
           String Autor = txt_autor.getText();
           String Genero = txt_genero.getText();
           String Editora = txt_editora.getText();
           System.out.println("Botão Cadastrar"); 
        }
        catch (NumberFormatException a) 
        {
            System.out.println("Erro no formato do valor");
            System.out.println(a.fillInStackTrace());
        }
        catch (Exception e)
        {
            System.out.println("ERRO!!! Foi mal :)");
            System.out.println(e.fillInStackTrace());
        }*/
        try {
            String driverName = "com.mysql.jdbc.Driver";
            Class.forName(driverName);
            String servidor = "193.123.108.138"; //caminho do servidor do BD
            String database = "progb2022"; //nome do banco de dados
            String url = "jdbc:mysql://" + servidor + "/" + database + "?useUnicode=true&characterEncoding=UTF8";
            System.out.println(url);
            String username = "progb2022";
            String senha = "progb2022";
            Connection conn = DriverManager.getConnection(url, username, senha);
            Statement stmt = conn.createStatement();
            int id = Integer.parseInt(txt_id.getText());
            String Livro      = txt_livro.getText();
            String Autor  = txt_autor.getText();
            String Genero = txt_genero.getText();
            String Editora = txt_editora.getText();
            String sql  = "INSERT INTO andrey_livro(id,livro,autor,genero,editora) VALUES('"+id+"','"+Livro+"','"+Autor+"','"+Genero+"','"+Editora+"');";
            System.out.println(sql);
            stmt.execute(sql);            ///preparaco da insercao do registro
            conn.close();
            System.out.println("Salvo no Banco");
            
            
            
        } catch (Exception e){
            System.out.println("erro"+e.getLocalizedMessage());
                        System.out.println("erro"+e.getStackTrace());
        }
        
    }//GEN-LAST:event_bt_cadastrarActionPerformed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        // TODO add your handling code here:
        try
        {
            System.out.println("Botão Pesquisar");
            String drivername = "com.mysql.jdbc.Driver"; /// driver
            String servidor   = "193.123.108.138"; // 
            String database   = "progb";
            String url        = "jdbc:mysql://193.123.108.138/progb2022";
            String usuario    = "progb2022";
            String senha      = "progb2022";
            Connection conexao  =  DriverManager.getConnection(url,usuario,senha);
            Statement stmt  =  conexao.createStatement();
            
            int id = Integer.parseInt(txt_id.getText());
            
            String consulta = "SELECT * FROM andrey_livro WHERE id = '"+id+"'";
            
            ResultSet rs = stmt.executeQuery(consulta);
            
            while (rs.next()) {
                System.out.println(" Livro : " + rs.getString("livro"));
                String livrol = rs.getString("livro");
                txt_livro.setText(livrol);
                
                System.out.println(" Autor : " + rs.getString("autor"));
                String autorl = rs.getString("autor");
                txt_autor.setText(autorl);
                
                System.out.println(" Genero : " +rs.getString("genero"));
                String generol = rs.getString("genero");
                txt_genero.setText (generol);
                
                System.out.println(" Editora : " + rs.getString("editora"));
                String editoral = rs.getString("editora");
                txt_editora.setText (editoral);
                
                
            }
            
             
             
             
             stmt.close();

        }
        catch (NumberFormatException a) 
        {
            System.out.println("Erro no formato do valor");
            System.out.println(a.fillInStackTrace());
        }
        catch (Exception e)
        {
            System.out.println("ERRO!!! Foi mal :)");
            System.out.println(e.fillInStackTrace());
        }
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void bt_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizarActionPerformed
        // TODO add your handling code here:
        try
        { 
            System.out.println("Botão Atualizar");
            String drivername = "com.mysql.jdbc.Driver"; /// driver
            String servidor   = "193.123.108.138"; // 
            String database   = "progb";
            String url        = "jdbc:mysql://193.123.108.138/progb2022";
            String usuario    = "progb2022";
            String senha      = "progb2022";
            Connection conexao  =  DriverManager.getConnection(url,usuario,senha);
            Statement stmt  =  conexao.createStatement();
            int id = Integer.parseInt(txt_id.getText());
            String Livro      = txt_livro.getText();
            String Autor  = txt_autor.getText();
            String Genero = txt_genero.getText();
            String Editora = txt_editora.getText();

            String sql = "UPDATE andrey_livro SET livro = '"+Livro+"',autor='"+Autor+"',genero='"+Genero+"',editora='"+Editora+"' WHERE ID = 42;";
            System.out.println(sql);
            stmt.execute(sql);
            stmt.close();
        }
        catch (NumberFormatException a) 
        {
            System.out.println("Erro no formato do valor");
            System.out.println(a.fillInStackTrace());
        }
        catch (Exception e)
        {
            System.out.println("ERRO!!! Foi mal :)");
            System.out.println(e.fillInStackTrace());
        }
    }//GEN-LAST:event_bt_atualizarActionPerformed

    private void bt_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarActionPerformed
        // TODO add your handling code here:
        try {
        String drivername = "com.mysql.jdbc.Driver"; /// driver
        String servidor   = "193.123.108.138"; // 
        String database   = "progb";
        String url        = "jdbc:mysql://193.123.108.138/progb2022";
        String usuario    = "progb2022";
        String senha      = "progb2022";
        Connection conexao  =  DriverManager.getConnection(url,usuario,senha);
        Statement stmt  =  conexao.createStatement();
        String sql = "DELETE FROM andrey_livro WHERE id = 1";
        System.out.println(sql);
        stmt.execute(sql);
        stmt.close();       
        
         
        } catch (Exception e) {
            System.out.println("Erro Generico = "+e.fillInStackTrace());
        }
    }//GEN-LAST:event_bt_deletarActionPerformed

    private void txt_livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_livroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_livroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Livro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_atualizar;
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_deletar;
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JLabel lbl_autor;
    private javax.swing.JLabel lbl_editora;
    private javax.swing.JLabel lbl_genero;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_livro;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_editora;
    private javax.swing.JTextField txt_genero;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_livro;
    // End of variables declaration//GEN-END:variables
}
