/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciamento_de_biblioteca;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author AndreyFernandesTraja
 */
public class F_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form F_Cliente
     */
    public F_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_cadastrar = new javax.swing.JButton();
        txt_nome = new javax.swing.JTextField();
        lbl_nome = new javax.swing.JLabel();
        txt_idade = new javax.swing.JTextField();
        lbl_idade = new javax.swing.JLabel();
        txt_telefone = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_endereco = new javax.swing.JTextField();
        lbl_telefone = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_endereco = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        bt_pesquisar = new javax.swing.JButton();
        bt_atualizar = new javax.swing.JButton();
        bt_deletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_cadastrar.setText("Cadastrar");
        bt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarActionPerformed(evt);
            }
        });

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        lbl_nome.setText("Nome:");

        txt_idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idadeActionPerformed(evt);
            }
        });

        lbl_idade.setText("Idade:");

        txt_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefoneActionPerformed(evt);
            }
        });

        lbl_telefone.setText("Telefone:");

        lbl_email.setText("Email:");

        lbl_endereco.setText("Endereço:");

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        lbl_id.setText("ID:");

        bt_pesquisar.setText("Pesquisar");
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        bt_atualizar.setText("Atualizar");
        bt_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atualizarActionPerformed(evt);
            }
        });

        bt_deletar.setText("Deletar");
        bt_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_endereco)
                    .addComponent(lbl_id)
                    .addComponent(lbl_nome)
                    .addComponent(lbl_idade)
                    .addComponent(lbl_email)
                    .addComponent(lbl_telefone))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(bt_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_atualizar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_deletar)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_telefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_idade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_idade)
                    .addComponent(txt_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefone)
                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_email)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_endereco)
                    .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cadastrar)
                    .addComponent(bt_pesquisar)
                    .addComponent(bt_atualizar)
                    .addComponent(bt_deletar))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarActionPerformed
        // TODO add your handling code here:
        
        /*try{
        Usuario u  =  new Usuario();
        int id = Integer.parseInt(txt_id.getText());
        String nome = txt_nome.getText();
        int idade = Integer.parseInt(txt_idade.getText());
        int telefone = Integer.parseInt(txt_telefone.getText());
        String email = txt_email.getText();
        String endereco = txt_endereco.getText();
        
        FileWriter arq = new FileWriter("d:\\User.txt");
        PrintWriter gravarArq = new PrintWriter(arq);
        arq.write(txt_id.getText());
        arq.write(";"); // da pra usar o printf
        arq.write(txt_nome.getText());
        gravarArq.printf(";"); // usei o printf
        arq.write(txt_idade.getText());
        arq.write(";");
        arq.write(txt_telefone.getText());
        arq.write(";");
        arq.write(txt_email.getText());
        arq.write(";");
        arq.write(txt_endereco.getText());
        arq.write(";");
        arq.close();*/
        
        //u.inserir(id, nome, idade, telefone, email, endereco);
        
        //System.out.println("Botão Cadastrar");
        //System.out.println(txt_nome.getText());
        //JOptionPane.showMessageDialog(null,"Botão clicado");
        //lbl_nome.setText("Andrey"); trocar o valor da variavel label - troca nome por Andrey
        /*System.out.println(txt_nome.getText());
        String nome = txt_nome.getText();
          if(nome.equalsIgnoreCase("Andrey"))
          {
              JOptionPane.showMessageDialog(null, "Acesso permitido");
          }
          else{
              JOptionPane.showMessageDialog(null, "Acesso não permitido");
          }    
        
        txt_idade.setText(txt_nome.getText());*/
        /*}
        catch (NumberFormatException a) 
        {
            System.out.println("Erro no formato do valor");
            System.out.println(a.fillInStackTrace());
        }
        catch (Exception e)
        {
            System.out.println("ERRO!!! Foi mal :)");
            System.out.println(e.fillInStackTrace());
        }*/
        try {
            String driverName = "com.mysql.jdbc.Driver";
            Class.forName(driverName);
            String servidor = "193.123.108.138"; //caminho do servidor do BD
            String database = "progb2022"; //nome do banco de dados
            String url = "jdbc:mysql://" + servidor + "/" + database + "?useUnicode=true&characterEncoding=UTF8";
            System.out.println(url);
            String username = "progb2022";
            String senha = "progb2022";
            Connection conn = DriverManager.getConnection(url, username, senha);
            Statement stmt = conn.createStatement();
            int id = Integer.parseInt(txt_id.getText());
            int idade = Integer.parseInt(txt_idade.getText());
            int telefone = Integer.parseInt(txt_telefone.getText());
            String nome = txt_nome.getText();
            String email = txt_email.getText();
            String endereco = txt_endereco.getText();
            String sql  = "INSERT INTO andrey_usuario(id,nome,idade,telefone,email,endereco) VALUES('"+id+"','"+nome+"','"+idade+"','"+telefone+"','"+email+"','"+endereco+"');";
            System.out.println(sql);
            stmt.execute(sql);            ///preparaco da insercao do registro
            conn.close();
            System.out.println("Salvo no Banco");
            
            
            
        } catch (Exception e){
            System.out.println("erro"+e.getLocalizedMessage());
                        System.out.println("erro"+e.getStackTrace());
        }
               
    }//GEN-LAST:event_bt_cadastrarActionPerformed

    private void txt_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefoneActionPerformed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        // TODO add your handling code here:
        try
        {
            System.out.println("Botão Pesquisar");
            String drivername = "com.mysql.jdbc.Driver"; /// driver
            String servidor   = "193.123.108.138"; // 
            String database   = "progb";
            String url        = "jdbc:mysql://193.123.108.138/progb2022";
            String usuario    = "progb2022";
            String senha      = "progb2022";
            Connection conexao  =  DriverManager.getConnection(url,usuario,senha);
            Statement stmt  =  conexao.createStatement();
            
            int id = Integer.parseInt(txt_id.getText());
            
            String consulta = "SELECT * FROM andrey_usuario WHERE id = '"+id+"'";
            
            ResultSet rs = stmt.executeQuery(consulta);
            
            while (rs.next()) {
                System.out.println(" Nome : " + rs.getString("nome"));
                String nome1 = rs.getString("nome");
                txt_nome.setText(nome1);
                
                System.out.println(" Endereço : " + rs.getString("endereco"));
                String enderecol = rs.getString("endereco");
                txt_endereco.setText(enderecol);
                
                System.out.println(" Email : " +rs.getString("email"));
                String emaill = rs.getString("email");
                txt_email.setText (emaill);
                
                System.out.println(" Telefone : " + rs.getString("telefone"));
                String telefonel = rs.getString("telefone");
                txt_telefone.setText (telefonel);
                
                System.out.println(" Idade : " + rs.getString("idade"));
                String idadel = rs.getString("idade");
                txt_idade.setText (idadel);
            }
            
             
             
             
             stmt.close();

        }
        catch (NumberFormatException a) 
        {
            System.out.println("Erro no formato do valor");
            System.out.println(a.fillInStackTrace());
        }
        catch (Exception e)
        {
            System.out.println("ERRO!!! Foi mal :)");
            System.out.println(e.fillInStackTrace());
        }
    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void bt_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atualizarActionPerformed
        // TODO add your handling code here:
        try
        {
            System.out.println("Botão Atualizar");
            String drivername = "com.mysql.jdbc.Driver"; /// driver
            String servidor   = "193.123.108.138"; // 
            String database   = "progb";
            String url        = "jdbc:mysql://193.123.108.138/progb2022";
            String usuario    = "progb2022";
            String senha      = "progb2022";
            Connection conexao  =  DriverManager.getConnection(url,usuario,senha);
            Statement stmt  =  conexao.createStatement();
            int id = Integer.parseInt(txt_id.getText());
            int idade = Integer.parseInt(txt_idade.getText());
            int telefone = Integer.parseInt(txt_telefone.getText());
            String nome = txt_nome.getText();
            String email = txt_email.getText();
            String endereco = txt_endereco.getText();

            String sql = "UPDATE andrey_usuario SET nome = '"+nome+"',idade='"+idade+"',telefone='"+telefone+"',email='"+email+"',endereco='"+endereco+"' WHERE ID = 42;";
            System.out.println(sql);
            stmt.execute(sql);
            stmt.close();
        }
        catch (NumberFormatException a) 
        {
            System.out.println("Erro no formato do valor");
            System.out.println(a.fillInStackTrace());
        }
        catch (Exception e)
        {
            System.out.println("ERRO!!! Foi mal :)");
            System.out.println(e.fillInStackTrace());
        }
    }//GEN-LAST:event_bt_atualizarActionPerformed

    private void bt_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarActionPerformed
        // TODO add your handling code here:
        try {
        String drivername = "com.mysql.jdbc.Driver"; /// driver
        String servidor   = "193.123.108.138"; // 
        String database   = "progb";
        String url        = "jdbc:mysql://193.123.108.138/progb2022";
        String usuario    = "progb2022";
        String senha      = "progb2022";
        Connection conexao  =  DriverManager.getConnection(url,usuario,senha);
        Statement stmt  =  conexao.createStatement();
        int id = Integer.parseInt(txt_id.getText());
        String sql = "DELETE FROM andrey_usuario WHERE (id) = '"+id+"'";
        System.out.println(sql);
        stmt.execute(sql);
        stmt.close();
        
         
        } catch (Exception e) {
            System.out.println("Erro Generico = "+e.fillInStackTrace());
        }
    }//GEN-LAST:event_bt_deletarActionPerformed

    private void txt_idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idadeActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_atualizar;
    private javax.swing.JButton bt_cadastrar;
    private javax.swing.JButton bt_deletar;
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_endereco;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_idade;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_telefone;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_endereco;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_idade;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
